### ISSUE TITLE
ACR phantom with 4 resolution inserts

### ISSUE THREAD

**Issue by MariaLiljeroth** [NHSH-MRI-Physics/Scottish-Medium-ACR-Analysis-Framework#16]
Hi, thanks for this it is a really nice front end to hazen, we have a medium ACR phantom from proMRI ( https://www.standardimaging.com/products/pro-mri-acr-phantom ) but it has 4 resolution inserts. Thus, the analysis fails for our resolution task. 
![RESOLUTION_INSET](https://github.com/user-attachments/assets/3a736c6a-b33b-4f16-8c82-401216506e62)

Could this be fixed? The other tasks tested so far work really well. I can send the .dcms if you let me know where to send them as they wouldn't attach

BW

Maria

**Comment by MariaLiljeroth** [comment]
![image](https://github.com/user-attachments/assets/418ba7ad-9fc6-4cb9-9bfa-d616f0526c8a)

![image](https://github.com/user-attachments/assets/c7e300ad-b0d4-4a5e-8353-efcb7ca94a99)
cmd line output: " Running SNR
Slice order inversion not required.
LR orientation swap not required.
Optimization terminated successfully.
         Current function value: -254873.000000
         Iterations: 49
         Function evaluations: 122
SNR :70.69
Normalised SNR :2760.1
Progress 1/7
Running Geometric Accuracy
Slice order inversion not required.
LR orientation swap not required.
Optimization terminated successfully.
         Current function value: -254873.000000
         Iterations: 49
         Function evaluations: 122
Slice 1 Hor Dist: 174.8    Vert Dist: 176.27
Slice 5 Hor Dist:176.27    Vert Dist:178.71    Diag SW Dist:176.76   Diag SE Dist:176.27
Progress 2/7
Running Spatial Resoloution
Slice order inversion not required.
LR orientation swap not required.
Optimization terminated successfully.
         Current function value: -254873.000000
         Iterations: 49
         Function evaluations: 122
Could not calculate the spatial resolution for IB_Ax_8_1 because of : Error: The number of found resolution square does not equal exactly 4.
Traceback (most recent call last):
  File "hazenlib\tasks\acr_spatial_resolution.py", line 128, in run
  File "hazenlib\tasks\acr_spatial_resolution.py", line 942, in get_ContrastResponse
  File "hazenlib\tasks\acr_spatial_resolution.py", line 81, in GetROICrops
  File "hazenlib\tasks\acr_spatial_resolution.py", line 670, in GetResSquares
Exception: Error: The number of found resolution square does not equal exactly 4.
Exception in Tkinter callback
Traceback (most recent call last):
  File "hazenlib\tasks\acr_spatial_resolution.py", line 128, in run
  File "hazenlib\tasks\acr_spatial_resolution.py", line 942, in get_ContrastResponse
  File "hazenlib\tasks\acr_spatial_resolution.py", line 81, in GetROICrops
  File "hazenlib\tasks\acr_spatial_resolution.py", line 670, in GetResSquares
Exception: Error: The number of found resolution square does not equal exactly 4.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1967, in __call__
  File "GUI.py", line 449, in RunAnalysis
  File "MedACRAnalysis.py", line 139, in RunAnalysis
  File "hazenlib\tasks\acr_spatial_resolution.py", line 150, in run
Exception: Error: The number of found resolution square does not equal exactly 4.
"
[IB_AX_0008.zip](https://github.com/user-attachments/files/17488982/IB_AX_0008.zip)

**Comment by DrSpacemanMD** [comment]
Hi Maria

I Had a look at your phantom data. Firstly it seems to be scanned back to front (which is part of the reason why it can’t find all 4 resolution blocks). Also, it seems to not be the same ACR style phantom we expect. In the image below you can see the differences in the first slice and on the second image you can see the distortion insert is also quite different

![image](https://github.com/user-attachments/assets/837685f9-e69c-4b83-99eb-1fcc98dbf000)
![image](https://github.com/user-attachments/assets/aa3f454f-70f2-4a78-95a3-9d87c5ad2370)

Looking at the link in your post it seems to suggest it should have a 3x3 holes array (like the one on the right), so I’m a bit surprised your DICOM shows the lines. 

Also, your DICOM dimensions are a bit strange, I expect the medium ACR to have a diameter of 165mm but yours seems to have a diameter of 175mm. This seems to be least part of the reason why the resolution is struggling (it relies on the geometry to find the squares). I'm not sure if this is caused by the distortion though, you can really see it in the first slice.

With that being said if you run the spatial res method as "MTF" and the Geo Acc method to "ACR Method" it does seem to give some reasonable results. Although since the phantom is different to what is expected it doesn't come with any guarantees!

Thanks

John

**Comment by MariaLiljeroth** [comment]
Hi John, so sorry i posted the wrong link. This ( as you discovered ) is ours: https://www.southernscientific.co.uk/products-by-manufacturer/diagnomatic/mri/pro-mri#technical-specifications. It would be great if it could, in the future be adapted to work with the distortion grid in case you see a lot of other people using the same acr phantom as us. Thanks again! /Maria
